name: org-trufflehog

on:
  workflow_dispatch:
  schedule:
    - cron: "23 10 3 * *"  # monthly (minute-safe policy)

permissions: read-all

jobs:
  trufflehog:
    uses: gr8monk3ys/org-workflows/.github/workflows/reusable-trufflehog.yml@2659a9a32c4e6e3858f69a2f502210941a886d5a
