name: org-release-please

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions: read-all

jobs:
  release-please:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: gr8monk3ys/org-workflows/.github/workflows/reusable-release-please.yml@2659a9a32c4e6e3858f69a2f502210941a886d5a
